# permissions for end users to edit blogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: blog-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-blog
    app.kubernetes.io/part-of: operator-blog
    app.kubernetes.io/managed-by: kustomize
  name: blog-editor-role
rules:
- apiGroups:
  - calderwd.com
  resources:
  - blogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calderwd.com
  resources:
  - blogs/status
  verbs:
  - get
